# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c8bca1f0153951382d60b657b65ec4443ea78b80ef5532c0fedc95674ccc49e1cf43a4e3c94c315d7555e4c5c180ba7d78eb96383ee0d23f5880fc5631ab3c98

test:
  secret_key_base: 2eac0acd90072a26c41b766e2de8ed02b11ea7b61de8437f72794e918d6ea035273a6ec6a48bb4019976475209ed60d92a34070646a9892f6a0abe52e8e74002

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
